
---
- name: Push Candidate Config
  template:
    src: '{{ config_template }}'
    dest: '/tmp/.{{ inventory_hostname }}.xml'

- name: Apply candidate config
  arrcus.arcos.arcos_config:
    src: "/tmp/.{{ inventory_hostname }}.xml"
    load_operation: merge
    comment: "initial config pushed by netsim"

- name: Remove temp file
  file:
   state: absent
   path: '/tmp/.{{ inventory_hostname }}.xml'

