#
# Fetch Cumulus VX configuration files
#
- command: vtysh -c 'show run'
  become: true
  register: config
- copy:
    content: |
      {{ config.stdout }}
    dest: "{{ config_dir }}/{{ inventory_hostname }}.cfg"
  delegate_to: localhost

- command: cat /etc/frr/daemons
  become: true
  register: config
- copy:
    content: |
      {{ config.stdout }}
    dest: "{{ config_dir }}/{{ inventory_hostname }}-daemons"
  delegate_to: localhost

- command: ifquery -a
  register: ifquery
  become: true
- copy:
    content: |
      {{ ifquery.stdout }}
    dest: "{{ config_dir }}/{{ inventory_hostname }}-interfaces"
  delegate_to: localhost
