#
# Deploy a model-specific configuration (specified in "item") to a device
#
- block:
  - debug:
      msg: |
        {{ item }} configuration for {{ inventory_hostname }}
        =========================================
        {{ lookup('template','../templates/'+item+'/'+ansible_network_os+'.j2') }}
      verbosity: 1

  - include_tasks: "deploy-config/{{ansible_network_os}}.yml"
    tags: [ always ]
    args:
      apply:
        vars:
          config_template: "../templates/{{ item }}/{{ansible_network_os}}.j2"

  tags: [ models ]
